spring.application.name=QuoraApiConstruction
spring.datasource.url=jdbc:mysql://localhost:3306/quoraBackend
spring.datasource.username=root
spring.datasource.password=Archita@27
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true